### ISSUE TITLE
Ruby 2.4.0 Error: Failed to apply catalog: private method `open' called for Augeas:Class

### ISSUE THREAD

**Issue by xaque208** [hercules-team/augeasproviders_core#6]
`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`

Running the most recent `augeas` gem, and `2.1.3` of this module, I get the following error.

```
$ puppet agent -t --trace
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for host.example.com
Info: Applying configuration version '13790f4f01245edc85ff6bb19cb39a9c86244a61'
Error: Failed to apply catalog: private method `open' called for Augeas:Class
Did you mean?  open3
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:70:in `aug_handler'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:670:in `augopen_internal'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:109:in `augopen'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/host/augeas.rb:45:in `get_resources'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/host/augeas.rb:62:in `block in prefetch'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/host/augeas.rb:62:in `each'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/host/augeas.rb:62:in `inject'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/host/augeas.rb:62:in `prefetch'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/transaction.rb:323:in `prefetch'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/transaction.rb:223:in `prefetch_if_necessary'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/transaction.rb:107:in `block in evaluate'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/graph/relationship_graph.rb:116:in `traverse'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/transaction.rb:154:in `evaluate'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/resource/catalog.rb:222:in `block in apply'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/util/log.rb:155:in `with_destination'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/transaction/report.rb:142:in `as_logging_destination'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/resource/catalog.rb:221:in `apply'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/configurer.rb:171:in `block in apply_catalog'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/util.rb:223:in `block in benchmark'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/util.rb:222:in `benchmark'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/configurer.rb:170:in `apply_catalog'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/configurer.rb:343:in `run_internal'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/configurer.rb:221:in `block in run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/context.rb:65:in `override'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet.rb:241:in `override'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/configurer.rb:195:in `run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent.rb:45:in `block (4 levels) in run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent/locker.rb:21:in `lock'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent.rb:45:in `block (3 levels) in run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent.rb:98:in `with_client'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent.rb:42:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent.rb:65:in `run_in_fork'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent.rb:41:in `block in run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/application.rb:179:in `controlled_run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/agent.rb:39:in `run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/application/agent.rb:353:in `onetime'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/application/agent.rb:331:in `run_command'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/application.rb:344:in `block in run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/util.rb:540:in `exit_on_fail'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/application.rb:344:in `run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/util/command_line.rb:132:in `run'
/usr/lib/ruby/vendor_ruby/2.4.0/puppet/util/command_line.rb:72:in `execute'
/usr/bin/puppet:5:in `<main>'
```

**Comment by domcleal** [comment]
You need the `ruby-augeas` gem and not the `augeas` gem. The latter is a form of the one maintained by @hercules-team, but it's incompatible as it presents a different API.
